apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi
  namespace: default
spec:
  endpoints:
  - port: http
    interval: 15s
  namespaceSelector:
  selector:
    matchLabels:
      app: api